# container 2 deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-container-2
  template:
    metadata:
      labels:
        app: k8s-container-2
    spec:
      containers:
        - name: container-2
          image: us-east1-docker.pkg.dev/kubernetes-428901/kubernetes-assignment/container-2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data-volume
              mountPath: /raj_PV_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: host-pvc
---
# container 2 service
apiVersion: v1
kind: Service
metadata:
  name: container-2-service
spec:
  selector:
    app: k8s-container-2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
