# container 1 deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-container-1
  template:
    metadata:
      labels:
        app: k8s-container-1
    spec:
      containers:
        - name: container-1
          image: us-east1-docker.pkg.dev/kubernetes-428901/kubernetes-assignment/container-1
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: data-volume
              mountPath: /raj_PV_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: host-pvc
---
# container 1 service
apiVersion: v1
kind: Service
metadata:
  name: container-1-service
spec:
  selector:
    app: k8s-container-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
  type: LoadBalancer
